# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
