# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt', '0002_user_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_user', models.ManyToManyField(related_name='user_item', to='python_belt.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adder', to='python_belt.User')),
            ],
        ),
    ]
